# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: fast

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.7
  - numpy

  - pip:
    - -r file:requirements.txt
